# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aca43a6a80de42db59a7ef46b3a49a70c10ada491d88da69ba2f944a5b38a0ff818fa3b844e7b9994585eb8a4bff0f94205fd3615638a6d801e3a6ca15852301

test:
  secret_key_base: 8622e99ab628e36da819eb74f773a8b703b116c9411a4416e8ea52d99c814a9e0ebd1843f14521b98cb8f7ac87bfe68ea0b9058a14452ae91b46ca1774233bea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
